version: '3'
services:

  redis-cluster:
    image: redis:latest
    command: redis-cli -p 7001 --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 127.0.0.1:7006 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    ports:
      - "47000:47000"
      - "57000:57000"
    network_mode: "host"

  redis-1:
    build: ./redis
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7001
    network_mode: "host"

  redis-2:
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7002
    network_mode: "host"

  redis-3:
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7003
    network_mode: "host"

  redis-4:
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7004
    network_mode: "host"

  redis-5:
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7005
    network_mode: "host"

  redis-6:
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7006
    network_mode: "host"
